[package]
authors = [ "CoBloX developers <team@coblox.tech>" ]
name = "tokio_noise_codec"
version = "0.1.0"

[dependencies]
byteorder = "1.3"
bytes = "0.4"
snow = "0.4"
tokio-codec = "0.1"
log = "0.4"

[dev-dependencies]
env_logger = "0.6"
spectral = "0.6"
